### ISSUE TITLE
Are we sure we don't need a Mac in order to use this?

### ISSUE THREAD

**Issue by BauRawson** [dulvui/godot-ios-upload#1]
Hi Simon! First of all thanks for this repo, it might be of great use. My Macbook died and this is the only ray of hope I've encountered to keep working on my iOS project.

I have my doubts that we can actually use these actions without a Mac with Xcode, though. As per this page: https://simondalvai.org/blog/godot-ios-upload/ 'It also brings the advantage that you don't need a Mac at all. So it saves you time and money, if you're not a Mac user.'

Disclaimer: I've never used GitHub Actions before, so maybe I'm just ignorant!

In here: https://github.com/dulvui/godot-ios-upload/blob/main/action.yml there's no 'jobs:' property, so I thought I'd use the one in your other examples.

In here: https://github.com/dulvui/pocket-broomball/blob/main/.github/workflows/upload-ios.yml we do have the 'jobs:' property, however it uses these fields:

  BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
  BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
  KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
  
Which as far as I can tell, one can only get by using a Mac with XCode. For example to create a certificate on the Apple Dev web, you need to create a Certificate Request, as far as I can tell that can only be done from a Mac.

So maybe those fields aren't 100% needed to create the build? Or do you know of a way to get those certificates using only the Apple Developer Web?

Thanks so much for your time!

**Comment by BauRawson** [comment]
Wait, I just found out you can create the certificate without a Mac!
I'll investigate some more and get back here with anything I find, in case it might help some other newbs

**Comment by dulvui** [comment]
Hi, nice to see more people using the Github Action!
You can create a certificate on a Linux machine or even Windows I think, because it's a standard encryption process that can be recreated with openssl.
I used this guide here, if I can remember right
https://gist.github.com/jcward/d08b33fc3e6c5f90c18437956e5ccc35

Github Actions can be a bit complicated at the beginning and hard to debug, so if you have more questions just open an issue :-)

A side-note: Github Actions are always free only on open source repositories. On private you get 2000 to 3000 run minutes per month depending of your type of account (if your repository is private). Additionally, macOS actions consume 10x minutes of a Linux machine, so you actually get 200 to 300 minutes per month.
Here the documentation about pricing https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions 

I will add the certificate steps and the pricing issue to the blog post and README for future users.
